server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.0.11
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4FzhN1DRoxAJMLGPDwYe # 你自己的accessKeyId
    accessKeySecret: PsJaZOdtwnQYPZUPbKUYxssUxaQYNy # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_190784260 # 模板名称