server:
  port: 10010
spring:
  application:
    name: itcast-zuul
zuul:
  routes:
    service-provider: /user/**
    service-consumer: /consumer/**
  prefix: /api
      # path: /service-provider/**
      # url: http://localhost:8082
      # serviceId: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka